"""Initial migration

Revision ID: fed1ee484cf2
Revises: 
Create Date: 2026-09-29 03:04:24.212314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed1ee484cf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_status', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_id')
    )
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('storage', sa.String(), nullable=True),
    sa.Column('colour', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('seller', sa.String(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.crawl_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_scraped_at'), ['scraped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_variant_id'), ['variant_id'], unique=False)

    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('offer_text', sa.String(), nullable=True),
    sa.Column('offer_type', sa.String(), nullable=True),
    sa.Column('bank', sa.String(), nullable=True),
    sa.Column('offer_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_purchase', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_cap', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('emi_available', sa.Boolean(), nullable=False),
    sa.Column('emi_tenure', sa.Integer(), nullable=True),
    sa.Column('emi_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('validity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_variant_id'))
        batch_op.drop_index(batch_op.f('ix_listing_source'))
        batch_op.drop_index(batch_op.f('ix_listing_scraped_at'))

    op.drop_table('listing')
    op.drop_table('crawl')
    # ### end Alembic commands ###
